# -*- coding: utf-8 -*-
"""AlphaVtgTutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b00JTbv1xT-j40PcrOi4CDi5dWFpkSSR

api for stock data

**Set Up Environment**
"""

pip install alpha_vantage

import pandas as pd
import matplotlib.pyplot as plt
from alpha_vantage.timeseries import TimeSeries

"""**Store API Key**"""

# 1Q1PRNGXN295CIBV

key = '1Q1PRNGXN295CIBV'

"""**Create Timeseries Object, Make API Call**"""

ts = TimeSeries(key,output_format='pandas')
data, meta = ts.get_intraday('TSLA',interval='1min', outputsize='full')

"""**Examine Data**"""

meta

data.info()

data.head()

plt.plot(data['4. close'])

"""**Rename columns and add seperate date and time columns**"""

columns = ['open', 'high', 'low', 'close', 'volume']
data.columns = columns

data['TradeDate'] = data.index.date
data['time'] = data.index.time

data.loc['2023-10-18']

market = data.between_time('09:30:00', '16:00:00').copy()
market.sort_index(inplace=True)
market.info()

market.groupby('TradeDate').agg({'low':min,'high':max})

market.loc[market.groupby('TradeDate')['low'].idxmin()]
# minute when lowest occurs

market.loc[market.groupby('TradeDate')['high'].idxmax()]
# minute when highest occurs